# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/salaa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),salaa)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,78a3e94ab2c7ae62b9e1179845134a804da6687a)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,0300eec0ab780e0cd8d1357293db4f6a67e35764)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,1e34db9123384ed743b67e881a9065f32c5e7cb7)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,3cb8d9babeedce03133b6d857d43d5e2cd003ea5)
$(call add-radio-file-sha1-checked,radio/cdt_engineering.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/gz.img,a97677169e47ea42c41d50bb36fceeaddc432b59)
$(call add-radio-file-sha1-checked,radio/lk.img,2b3386b8f00b9f218b2a863867ef065e82418c3a)
$(call add-radio-file-sha1-checked,radio/logo.bin,e625002c3a10cf05d0e365d974010c188ae246b9)
$(call add-radio-file-sha1-checked,radio/md1img.img,4da23e2f2a308d1e322b68167ec3cb207b0fd2d6)
$(call add-radio-file-sha1-checked,radio/preloader_ufs.img,c39637205f4a216f1f545154555909803eba4c9b)
$(call add-radio-file-sha1-checked,radio/scp.img,22fceddfc61e5aa04efe1f7d0b2c21a831743ada)
$(call add-radio-file-sha1-checked,radio/spmfw.img,a030ab976d1ed30bba13d0948f6f2318a1c9534d)
$(call add-radio-file-sha1-checked,radio/sspm.img,2092ada5baee39ec902831778bc621ebe5f1c877)
$(call add-radio-file-sha1-checked,radio/tee.img,aabd0e4dc80bdcdf5f02729a55d8c90a431e15ce)

endif
